# =============================================================================
# clone_study_components.R  (server)   [Refactor 11.11]
# -----------------------------------------------------------------------------
# SHALLOW clone of a whole study into a NEW (project_id, study_accession): copies
# the raw xmap_* tables, the curve_lookup registry, and the study's calib_settings
# overrides. Fitted calib_* results are intentionally NOT copied -- the clone is
# re-fit via a Compute-fits job. Counterpart to delete_study_components.R; reuses
# .tbl() / CALIB_RAW_TABLES from calib_data_access.R (source AFTER it).
#
# Identity is regenerated by the DATABASE, so no id-remap is needed:
#   * curve_lookup.curve_id is GENERATED ALWAYS AS IDENTITY  -> omitted on insert.
#   * curve_lookup.multiplate_group_id is set by the BEFORE-INSERT trigger
#     trg_set_multiplate_group_id from the (new) scope columns -> omitted so the
#     clone gets fresh group ids, grouped exactly as a fresh import would.
# Every cloned table is re-scoped by (project_id, study_accession); columns are
# introspected so auto-generated PKs (IDENTITY and serial/nextval) are dropped and
# reassigned. All inserts run inside ONE transaction.
#
# ASSUMPTION (verify with a test clone): the xmap_* rows are self-contained by
# scope/natural key -- no xmap_* table references another via a SURROGATE id. That
# holds for delete (which removes them by scope in any order); if a surrogate FK
# link ever exists, that pair would need an explicit old->new id map here.
# =============================================================================

.clone_schema <- function() sub("\\..*$", "", .tbl("curve_lookup"))

# tables cloned by (project_id, study_accession). Includes the three annotation
# tables: .clone_rescope() rewrites only project_id + study_accession and copies
# every other column verbatim, so experiment_accession and all descriptive fields
# carry over. They key on the natural key (no surrogate IDENTITY id), so they
# re-scope cleanly just like the xmap_* tables.
.CLONE_TABLES <- c("curve_lookup", unname(CALIB_RAW_TABLES),
                   "xmap_dilution_analysis", "xmap_antigen_family",
                   "xmap_dilution_parameters", "xmap_study_config",
                   "annotation_analyte", "annotation_level", "annotation_order")
# curve_lookup additionally drops its trigger-managed group id
.clone_exclude <- function(tbl) if (identical(tbl, "curve_lookup")) "multiplate_group_id" else character(0)

# copyable columns: skip IDENTITY and serial (nextval) PKs so the DB reassigns them
.clone_cols <- function(co, tbl, exclude = character(0)) {
  nm <- sub("^.*\\.", "", .tbl(tbl))
  cols <- DBI::dbGetQuery(co,
    "SELECT column_name FROM information_schema.columns
      WHERE table_schema = $1 AND table_name = $2 AND is_identity = 'NO'
        AND (column_name = 'workspace_id'
             OR column_default IS NULL OR column_default NOT LIKE 'nextval(%')
      ORDER BY ordinal_position", params = list(.clone_schema(), nm))$column_name
  setdiff(cols, exclude)
}

# INSERT ... SELECT one table re-scoped to (newproj, newstudy). Returns row count.
.clone_rescope <- function(co, tbl, newproj, newstudy, srcproj, srcstudy) {
  cols <- .clone_cols(co, tbl, .clone_exclude(tbl))
  if (!length(cols)) return(0L)
  q <- function(c) as.character(DBI::dbQuoteIdentifier(co, c))
  sel <- vapply(cols, function(c)
    if (identical(c, "project_id")) "$1::integer"
    else if (identical(c, "workspace_id")) "$1::bigint"   # legacy synonym of project_id
    else if (identical(c, "study_accession")) "$2::character varying"
    else q(c), character(1))
  DBI::dbExecute(co, sprintf(
    "INSERT INTO %s (%s) SELECT %s FROM %s
       WHERE project_id IS NOT DISTINCT FROM $3 AND study_accession = $4",
    .tbl(tbl), paste(vapply(cols, q, character(1)), collapse = ", "),
    paste(sel, collapse = ", "), .tbl(tbl)),
    params = list(newproj, newstudy, srcproj, srcstudy))
}

# study-scoped calib_settings only (the study filter excludes system/project tiers,
# whose study_accession is '__none__'); re-scoped to (newproj, newstudy).
.clone_settings <- function(co, newproj, newstudy, srcproj, srcstudy)
  .clone_rescope(co, "calib_settings", newproj, newstudy, srcproj, srcstudy)

# does the target scope already hold data? (collision guard)
.clone_target_exists <- function(conn, proj, study) {
  n <- function(tb) tryCatch(as.integer(DBI::dbGetQuery(conn, sprintf(
    "SELECT count(*) FROM %s WHERE project_id IS NOT DISTINCT FROM $1 AND study_accession = $2",
    .tbl(tb)), params = list(proj, study))[[1]]), error = function(e) 0L)
  (n("curve_lookup") + n("xmap_header")) > 0L
}

# dry-run: rows that WOULD be cloned, per source table
count_clone_source <- function(conn, srcproj, srcstudy) {
  cnt <- function(tb) tryCatch(as.integer(DBI::dbGetQuery(conn, sprintf(
    "SELECT count(*) FROM %s WHERE project_id IS NOT DISTINCT FROM $1 AND study_accession = $2",
    .tbl(tb)), params = list(srcproj, srcstudy))[[1]]), error = function(e) NA_integer_)
  out <- vapply(c(.CLONE_TABLES, "calib_settings"), cnt, integer(1))
  out[!is.na(out)]
}

# the clone, atomic
clone_study_components <- function(conn, srcproj, srcstudy, newproj, newstudy, auth0_user = NA_character_) {
  stopifnot(!is.null(srcstudy), nzchar(srcstudy), !is.null(newstudy))
  newstudy <- trimws(newstudy)
  if (!nzchar(newstudy)) stop("Target study name is required.", call. = FALSE)
  if (nchar(newstudy) > 15)
    stop("Target study name must be <= 15 characters (study_accession is varchar(15)).", call. = FALSE)
  npn <- suppressWarnings(as.numeric(newproj))
  if (is.na(npn) || npn != round(npn)) stop("Target project_id must be a whole number.", call. = FALSE)
  newproj <- as.integer(npn)
  if (newproj < 16 || newproj > 32767)
    stop("Target project_id must be a small integer in 16..32767.", call. = FALSE)

  run_txn <- function(co) {
    # target project must already exist (need its name for the xmap_users grant)
    pname <- tryCatch(DBI::dbGetQuery(co,
      "SELECT project_name FROM madi_lumi_users.projects WHERE project_id = $1",
      params = list(newproj))$project_name, error = function(e) character(0))
    if (!length(pname))
      stop(sprintf("Target project_id %s does not exist in madi_lumi_users.projects; create it first.",
                   newproj), call. = FALSE)
    pname <- pname[[1]]

    if (.clone_target_exists(co, newproj, newstudy))
      stop(sprintf("Target (project %s, study '%s') already has data; refusing to clone into it.",
                   newproj, newstudy), call. = FALSE)

    ins <- integer(0)
    for (tb in .CLONE_TABLES)
      ins[[tb]] <- .clone_rescope(co, tb, newproj, newstudy, srcproj, srcstudy)
    ins[["calib_settings"]] <- .clone_settings(co, newproj, newstudy, srcproj, srcstudy)

    # Immediate visibility: point the current user at the new workspace. The
    # study list joins xmap_header.workspace_id -> xmap_users.workspace_id, so
    # without this row the clone is invisible even though the data exists.
    # Idempotent additional row (the durable ACL is madi_lumi_users.project_users,
    # managed separately; the next project-load may rewrite this pointer).
    ins[["xmap_users"]] <- if (is.character(auth0_user) && length(auth0_user) &&
                              !is.na(auth0_user) && nzchar(auth0_user))
      DBI::dbExecute(co, sprintf(
        "INSERT INTO %s (auth0_user, project_name, workspace_id)
           SELECT $1, $2, $3
            WHERE NOT EXISTS (SELECT 1 FROM %s WHERE auth0_user = $1 AND workspace_id = $3)",
        .tbl("xmap_users"), .tbl("xmap_users")),
        params = list(auth0_user, pname, newproj))
      else 0L
    ins
  }

  if (inherits(conn, "Pool")) {
    co <- pool::poolCheckout(conn); on.exit(pool::poolReturn(co), add = TRUE)
  } else co <- conn
  DBI::dbBegin(co)
  tryCatch({ r <- run_txn(co); DBI::dbCommit(co); r },
           error = function(e) {
             DBI::dbRollback(co)
             stop(sprintf("clone_study_components failed (rolled back): %s",
                          conditionMessage(e)), call. = FALSE)
           })
}

# =============================================================================
# Server wiring (top-level, sourced local=TRUE, matching delete_study_components).
# Source study comes from the sidebar (input$readxMap_study_accession) + the
# current workspace project (userWorkSpaceID()); the user types the TARGET project
# id + study name. Two-step confirm: Preview -> Clone -> shinyalert.
# =============================================================================

clone_preview_counts <- reactiveVal(NULL)

observeEvent(list(input$readxMap_study_accession,
                  input$clone_target_project, input$clone_target_study), {
  clone_preview_counts(NULL)
}, ignoreInit = TRUE)

.clone_target_study_str <- function() {
  v <- input$clone_target_study
  if (is.null(v)) "" else trimws(v)
}

observeEvent(input$clone_preview, {
  study <- input$readxMap_study_accession
  proj  <- tryCatch(userWorkSpaceID(), error = function(e) NA)
  if (is.null(study) || identical(study, "Click here") || is.na(study)) {
    showNotification("Choose a source study in the sidebar first.", type = "warning"); return()
  }
  tpn    <- suppressWarnings(as.numeric(input$clone_target_project))
  tproj  <- if (is.na(tpn)) NA_integer_ else as.integer(round(tpn))
  tstudy <- .clone_target_study_str()
  if (is.na(tpn) || tpn != round(tpn) || tproj < 16 || tproj > 32767) {
    showNotification("Target project id must be a small integer in 16..32767.", type = "warning"); return() }
  if (!nzchar(tstudy)) {
    showNotification("Enter a target study name.", type = "warning"); return() }
  if (nchar(tstudy) > 15) {
    showNotification("Target study name must be <= 15 characters.", type = "warning"); return() }
  pexists <- tryCatch(nrow(DBI::dbGetQuery(db_pool,
    "SELECT 1 FROM madi_lumi_users.projects WHERE project_id = $1", params = list(tproj))) > 0,
    error = function(e) FALSE)
  if (!isTRUE(pexists)) {
    showNotification(sprintf("Target project %s does not exist \u2014 create it first.", tproj),
                     type = "error", duration = NULL); return() }
  if (isTRUE(tryCatch(.clone_target_exists(db_pool, tproj, tstudy), error = function(e) FALSE))) {
    showNotification(sprintf("Target (project %s, study '%s') already has data.", tproj, tstudy),
                     type = "error", duration = NULL); return() }
  counts <- tryCatch(
    count_clone_source(db_pool, srcproj = proj, srcstudy = study),
    error = function(e) { showNotification(paste("Preview failed:", conditionMessage(e)),
                                           type = "error", duration = NULL); NULL })
  clone_preview_counts(counts)
})

output$clone_blast <- DT::renderDataTable({
  counts <- clone_preview_counts()
  if (is.null(counts)) {
    df <- data.frame(Message = "Enter the target project + study, then click Preview.")
    return(DT::datatable(df, rownames = FALSE, options = list(dom = "t")))
  }
  nz <- counts[counts > 0]
  df <- if (!length(nz)) data.frame(table = "(nothing to clone for this study)", rows = 0L)
        else data.frame(table = names(nz), rows = as.integer(nz), row.names = NULL)
  if (length(nz)) df <- rbind(df, data.frame(table = "TOTAL", rows = as.integer(sum(nz))))
  DT::datatable(df, rownames = FALSE, options = list(dom = "t", pageLength = 100, ordering = FALSE))
})

output$clone_confirm_ui <- renderUI({
  counts <- clone_preview_counts()
  if (is.null(counts) || !any(counts > 0)) return(NULL)
  tagList(
    tags$hr(),
    div(class = "alert alert-info",
        sprintf("Clone %s into project %s / study '%s' (%d rows). Fitted results are NOT copied \u2014 re-run Compute-fits on the clone.",
                input$readxMap_study_accession, input$clone_target_project,
                .clone_target_study_str(), as.integer(sum(counts)))),
    actionButton("clone_do", tagList(icon("clone"), "Clone study"), class = "btn-primary")
  )
})

observeEvent(input$clone_do, {
  counts <- clone_preview_counts()
  if (is.null(counts) || !any(counts > 0)) return()
  shinyalert::shinyalert(
    title = "Confirm clone",
    text = sprintf("Clone %s into project %s / study '%s'?\n\n%d rows copied. Fitted results are not copied.",
                   input$readxMap_study_accession, input$clone_target_project,
                   .clone_target_study_str(), as.integer(sum(counts))),
    type = "info", showCancelButton = TRUE,
    confirmButtonText = "Yes, clone", cancelButtonText = "Cancel", inputId = "clone_confirm")
})

observeEvent(input$clone_confirm, {
  req(isTRUE(input$clone_confirm))
  study  <- input$readxMap_study_accession
  proj   <- tryCatch(userWorkSpaceID(), error = function(e) NA)
  tproj  <- suppressWarnings(as.integer(input$clone_target_project))
  tstudy <- .clone_target_study_str()
  who    <- tryCatch(currentuser(), error = function(e) NA_character_)
  shinybusy::show_modal_spinner(spin = "fading-circle", color = "#337ab7",
                                text = "Cloning study... please wait.")
  res <- tryCatch(
    clone_study_components(db_pool, srcproj = proj, srcstudy = study,
                           newproj = tproj, newstudy = tstudy, auth0_user = who),
    error = function(e) e)
  shinybusy::remove_modal_spinner()
  if (inherits(res, "error")) {
    shinyalert::shinyalert("Clone failed", conditionMessage(res), type = "error"); return()
  }
  clone_preview_counts(NULL)
  total <- as.integer(sum(unlist(res)))
  shinyalert::shinyalert(
    title = "Cloned",
    text = sprintf("Copied %d rows into project %s / study '%s'.\n\nRe-run Compute-fits to fit the clone; refresh the study list to see it.",
                   total, tproj, tstudy),
    type = "success")
})
